//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace BGU.Web20.MiscItemsSite.Controls {
    
    
    public partial class BankInfoEditControl {
        
        /// <summary>
        /// tabs control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl tabs;
        
        /// <summary>
        /// tbOne control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl tbOne;
        
        /// <summary>
        /// tbTwo control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl tbTwo;
        
        /// <summary>
        /// tbPnlOne control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl tbPnlOne;
        
        /// <summary>
        /// uabkcbx control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::BGU.Web20.MiscItemsSite.Controls.RcuKruLookupControl3 uabkcbx;
        
        /// <summary>
        /// tbPnlTwo control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl tbPnlTwo;
        
        /// <summary>
        /// ddlCountry control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::BGU.Web20.MiscItemsSite.Controls.BootstrapDropDownBasic ddlCountry;
        
        /// <summary>
        /// edHeadMFO control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::BGU.Web20.MiscItemsSite.Controls.BootstrapTextEditBasic edHeadMFO;
        
        /// <summary>
        /// edRegistryNr control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::BGU.Web20.MiscItemsSite.Controls.BootstrapTextEditBasic edRegistryNr;
        
        /// <summary>
        /// edCode control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::BGU.Web20.MiscItemsSite.Controls.BootstrapTextEditBasic edCode;
        
        /// <summary>
        /// edName control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::BGU.Web20.MiscItemsSite.Controls.BootstrapTextEditBasic edName;
        
        /// <summary>
        /// edNameUkr control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::BGU.Web20.MiscItemsSite.Controls.BootstrapTextEditBasic edNameUkr;
        
        /// <summary>
        /// edSWIFTBIC control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::BGU.Web20.MiscItemsSite.Controls.BootstrapTextEditBasic edSWIFTBIC;
        
        /// <summary>
        /// hdATb control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField hdATb;
    }
}
